apiVersion: v1
baseDomain: example.com
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ocp4
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    vcenter: vcenter.example.com
    username: administrator@example.com
    password: MyStrongP4ssword
    datacenter: DC
    defaultDatastore: datastore1
fips: false
pullSecret: '{"auths":{"quay.io":{"auth":"yadayada=","email":"alexgd.devops@gmail.com"},"registry.connect.redhat.com":{"auth":"yadayada","email":"alexgd.devops@gmail.com"},"registry.redhat.io":{"auth":"yadayada","email":"alexgd.devops@gmail.com"}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9PQu0oUmKlMU/AS6PljqNF9cyX+x2JpV0nh8D0N1ztevlIo7MZ1Mm8vKmJ4ySJtE3VTpgZjpO14WfTFhfwVX0AHosDydAyq/E2XL0rVvT8Dz1QFcelHPt8Q0yMipzeOitDf6nr9Tme0q7RoLPavCdZQ+efRJ02mmFj3MR6uayjQqifrPc5t8rIQbSKUm0gDITEOkoP9LKtZgbR3n1QgK7/W2mwfCltwK03PrKLP+CW5Z912YQnSFtzXdvVTAM4FADvUTs8/wYQIUlBj1JFv0lY3BY/m8LyC1azJ39aUGmjcxVPPtDLGRlhoJJ6sZncaRzOUcU6rRkHDbRu3y1AEBL'
